spring:
  application:
    name: gateway

server:
  port: 8084

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full

services:
  application:
    url: http://localhost:8082
  deal:
    url: http://localhost:8081

logging:
  level:
    com.example.gateway: DEBUG